[package]
name = "databend-enterprise-dynamic-table"
description = "dynamic table handler"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]

[dependencies]

[build-dependencies]
